apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crdzero.domain1
spec:
  group: domain1
  names:
    kind: crdzero
    listKind: crdzeroList
    plural: crdzeros         # /apis/<group>/<version>/<plural>
    singular: crdzero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
  Validation:        # apply openAPIV3Schema Rule
    openAPIV3Schema:
      properties:
        spec:
          properties:
            # field: fieldA type integer, 1 <= fieldA <= 10
            fieldA:
              type: integer
              minimum: 1
              maximum: 10

