FROM hub.tess.io/sherlockio/debian:stretch

RUN mkdir -p /platform

RUN ls -l /workspace/repo/output

RUN ls -l /workspace/repo/output/crd_controller

RUN ls -l /bin

WORKDIR /workspace/repo

COPY output/crd_controller /bin/crd_controller

WORKDIR /platform

ENTRYPOINT [ "/bin/crd_controller" ]
CMD []