FROM hub.tess.io/sherlockio/debian:stretch

RUN mkdir -p /platform

WORKDIR /workspace/repo

RUN ls

RUN ls ./output

COPY ./output/crd_controller /bin/crd_controller

WORKDIR /platform

ENTRYPOINT [ "/bin/crd_controller" ]
CMD []