apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: crdcontroller
  name: crdcontroller
  namespace: ciaas-test
spec:
  replicas: 1
  selector:
    app: crdcontroller
  template:
    metadata:
      labels:
        app: crdcontroller
      name: crdcontroller
    spec:
      containers:
        - image: hub.tess.io/ydong/crd_controller:0.1
          imagePullPolicy: Always
          name: crdcontroller
          ports:
            - containerPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30