// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfig) DeepCopyInto(out *CiConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Status = in.Status
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfig.
func (in *CiConfig) DeepCopy() *CiConfig {
	if in == nil {
		return nil
	}
	out := new(CiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigList) DeepCopyInto(out *CiConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CiConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigList.
func (in *CiConfigList) DeepCopy() *CiConfigList {
	if in == nil {
		return nil
	}
	out := new(CiConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigSpec) DeepCopyInto(out *CiConfigSpec) {
	*out = *in
	in.Strategy.DeepCopyInto(&out.Strategy)
	out.Source = in.Source
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigSpec.
func (in *CiConfigSpec) DeepCopy() *CiConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CiConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigSpecSource) DeepCopyInto(out *CiConfigSpecSource) {
	*out = *in
	out.Git = in.Git
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigSpecSource.
func (in *CiConfigSpecSource) DeepCopy() *CiConfigSpecSource {
	if in == nil {
		return nil
	}
	out := new(CiConfigSpecSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigSpecSourceGit) DeepCopyInto(out *CiConfigSpecSourceGit) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigSpecSourceGit.
func (in *CiConfigSpecSourceGit) DeepCopy() *CiConfigSpecSourceGit {
	if in == nil {
		return nil
	}
	out := new(CiConfigSpecSourceGit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigSpecStrategy) DeepCopyInto(out *CiConfigSpecStrategy) {
	*out = *in
	out.StandardBuild = in.StandardBuild
	out.Master = in.Master
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]CiConfigSpecStrategyEnv, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigSpecStrategy.
func (in *CiConfigSpecStrategy) DeepCopy() *CiConfigSpecStrategy {
	if in == nil {
		return nil
	}
	out := new(CiConfigSpecStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigSpecStrategyEnv) DeepCopyInto(out *CiConfigSpecStrategyEnv) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigSpecStrategyEnv.
func (in *CiConfigSpecStrategyEnv) DeepCopy() *CiConfigSpecStrategyEnv {
	if in == nil {
		return nil
	}
	out := new(CiConfigSpecStrategyEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigSpecStrategyMaster) DeepCopyInto(out *CiConfigSpecStrategyMaster) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigSpecStrategyMaster.
func (in *CiConfigSpecStrategyMaster) DeepCopy() *CiConfigSpecStrategyMaster {
	if in == nil {
		return nil
	}
	out := new(CiConfigSpecStrategyMaster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigSpecStrategyStandardBuild) DeepCopyInto(out *CiConfigSpecStrategyStandardBuild) {
	*out = *in
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigSpecStrategyStandardBuild.
func (in *CiConfigSpecStrategyStandardBuild) DeepCopy() *CiConfigSpecStrategyStandardBuild {
	if in == nil {
		return nil
	}
	out := new(CiConfigSpecStrategyStandardBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigSpecStrategyStandardBuildSpec) DeepCopyInto(out *CiConfigSpecStrategyStandardBuildSpec) {
	*out = *in
	out.Stack = in.Stack
	out.Identifiers = in.Identifiers
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigSpecStrategyStandardBuildSpec.
func (in *CiConfigSpecStrategyStandardBuildSpec) DeepCopy() *CiConfigSpecStrategyStandardBuildSpec {
	if in == nil {
		return nil
	}
	out := new(CiConfigSpecStrategyStandardBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigSpecStrategyStandardBuildSpecIdentifier) DeepCopyInto(out *CiConfigSpecStrategyStandardBuildSpecIdentifier) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigSpecStrategyStandardBuildSpecIdentifier.
func (in *CiConfigSpecStrategyStandardBuildSpecIdentifier) DeepCopy() *CiConfigSpecStrategyStandardBuildSpecIdentifier {
	if in == nil {
		return nil
	}
	out := new(CiConfigSpecStrategyStandardBuildSpecIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigSpecStrategyStandardBuildSpecStack) DeepCopyInto(out *CiConfigSpecStrategyStandardBuildSpecStack) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigSpecStrategyStandardBuildSpecStack.
func (in *CiConfigSpecStrategyStandardBuildSpecStack) DeepCopy() *CiConfigSpecStrategyStandardBuildSpecStack {
	if in == nil {
		return nil
	}
	out := new(CiConfigSpecStrategyStandardBuildSpecStack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiConfigStatus) DeepCopyInto(out *CiConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiConfigStatus.
func (in *CiConfigStatus) DeepCopy() *CiConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CiConfigStatus)
	in.DeepCopyInto(out)
	return out
}
